### ISSUE TITLE
What does "it" mean?

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#18]
In 5.3 of LCP

> Since it is product of the calculation, the `signature` object of the License Document <b>MUST</b> be removed.

What does this "it" mean?.  This is not the only confusing use of "it" in this spec.

**Comment by murata2makoto** [comment]
All occurrences of "it" in 5.5.1 are confusing.

**Comment by llemeurfr** [comment]
Well, "it" logically refers to the signature object in this sentence. 

Re. 5.5.1, I agree that the first "It" has no meaning. After replacement by "The Reading System" as in 5.5.2, I believe the next bullets make sense ("It" being the Reading system).

**Comment by murata2makoto** [comment]
Then,

**Comment by llemeurfr** [comment]
good for me.
