### ISSUE TITLE
UTF-8 (United Character Set code point value)

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#19]
This phrase in LCP is very confusing.   Unicode ["code point"](https://www.unicode.org/glossary/#code_point) is correct.

**Comment by llemeurfr** [comment]
I propose to change the wording as: 
All object members (name/value pairs) of the License Document <b class="rfc">must</b> be sorted in lexicographical order of their names according to their representation as Unicode code point.

**Comment by danielweck** [comment]
>  All object members (name/value pairs) of the License Document must be sorted in lexicographical order of their names according to their representation as Unicode code point.

* Instead of "members" I would use the term "properties".
* Instead of "name" I would use the term "key".

See: https://json-schema.org/understanding-json-schema/reference/object.html

So I would like to propose:

> The JSON object properties (i.e. key/value pairs) in the License Document must be lexicographically sorted by unicode codepoint.

Also see: https://matrix.org/docs/spec/appendices#canonical-json
