### ISSUE TITLE
Congratulations!!

### ISSUE THREAD

**Issue by billrosenblatt** [readium/lcp-specs#2]
After lurking on this thread for quite some time and then seeing a live demo, I just wanted to offer my sincere congratulations to everyone for this great achievement. 

As a consultant, I am accustomed to a model of doing my thing, then riding off into the sunset.*  Most often I make recommendations or create requirements and then nothing happens, I don't hear about it any further, or both.  This is one of those rare occasions where not only did something great happen but I got to witness it.  It's obvious that several people did a lot of hard work, and it's going to benefit publishers, libraries, services for the print challenged, retailers, etc., etc.

Mes sincere felicitations et admiration a tous.  

- bill.

*This is an old American TV reference.  I'd be curious if anyone recognizes it.

**Comment by llemeurfr** [comment]
Thanks a lot Bill! 
And many thanks to Hadrien, Jean-Philippe, James, Stefaan, Daniel, Cyrille, Jean-Marie, Michael, Artem, Taehyun, Rémi, Hanna, Bastien (I hope I don't forget somebody) who helped 
on the specification and codebase. 

note: strange to use a github issue for such a message. But ok.

**Comment by billrosenblatt** [comment]
Yes though this Github thread seemed to be the best place for a message to reach the developers who did the "real work."

- bill.
