### ISSUE TITLE
Use of "+" should be prohibited

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#20]
In 5.3 of LCP, the use of "+" should be prohibited.

**Comment by llemeurfr** [comment]
@murata2makoto can you please detail this request? 
The initial state, before canonicalization, is a well-formed json. Where is the '' sign involved then?

**Comment by murata2makoto** [comment]
I'm afraid that I cannot recall the reason for my comment.  Agree to close this issue.
