### ISSUE TITLE
Escaping of control characters (U+0000 through U+001F)

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#21]
Are all characters  from U+0000 to U+001F escaped?  Including carriage returns, line feeds, or tabs?

**Comment by llemeurfr** [comment]
If the context of your question is the canonicalization of the manifest, the initial state of the manifest is being a well-formed JSON structure, with carriage return etc. properly represented.

**Comment by llemeurfr** [comment]
Resolved during a meeting in Japan.
