### ISSUE TITLE
"a valid license <b>MAY</b> be created" in 5.4 of LCP

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#23]
First, since this subsection is informative, the use of "MUST", "SHALL", "MAY", etc. should be avoided.  Second, this sentence sounds very strange to me.    We always create a valid license here.

**Comment by llemeurfr** [comment]
Proposal, the wording becomes: 
"With this signature and the certificate, a valid license will be created as e.g.:"
