### ISSUE TITLE
Use of algorithms not defined in [XML-ENC] or [XML-SIG].

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#26]
> All algorithms used in an Encryption Profile MUST be defined in [XML-ENC] or [XML-SIG].

This sentence appears to disallow the use of Camellia, for example.  Is this intentional?

**Comment by llemeurfr** [comment]
I guess we can agree that this is ok for now, and that if Camellia is to be used in the future, we will relax the spec to deal with it.

**Comment by murata2makoto** [comment]
I do not agree.  

How about "SHOULD" rather than "MUST"?

**Comment by llemeurfr** [comment]
> How about "SHOULD" rather than "MUST"?
This is not harmful, as the Encryption Profile defines which algorithms are used.
