### ISSUE TITLE
Registries should be normative rather than informative

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#27]
All registries have to be made normative, since some normative requirements rely on them.  Even if they are empty at present, there should be blank HTML documents for these registries.

**Comment by llemeurfr** [comment]
I tend to not agree. For instance the "1.0" (aka Production  1.0) profile will be in the encryption profile registry and it cannot be made normative. Same for vendor-specific extensions which may be added to the same registry.

**Comment by HadrienGardeur** [comment]
The requirements should be defined in the specifications themselves and registry by nature should be informative, to be flexible enough whenever we need to update them outside a revision cycle.

**Comment by murata2makoto** [comment]
ISO/IEC has highly-demanding rules about registries.  It is practically impossible to create an International Standard that uses registries.  If you would like to know the details of the rules, I can.  But I would like to say that Japan recently gave up standardization, since new rules require even higher burden.  Are you willing to pay an insurance fee?

If you would like to create an International Standard eventually, it is a very good idea to drop registries entirely from LCP.  If a TS is good enough for now, we can probably publish a TS without dropping registries.

References to registries are normative.  If they are informative, they should be dropped entirely without any problems.

**Comment by llemeurfr** [comment]
LCP as an ISO TS (Technical Spec) is the current goal. 

In your description of constraints on registries, you say that we should drop registries in order to have LCP as an ISO International Standard. If we decide to go there this will not be difficult to remove registries from the spec, as they are informative: all the necessary information is in the spec, most registries replicate this information. Only the Encryption Profile contains extra-information, which is the identifier of the "production" profile.

**Comment by llemeurfr** [comment]
Note also that because most registries replicate what is in the spec, and because the "production" Profile is identified in EDRLab documentation for LCP implementers, I'm not a fan of these registries (I don't know what is their practical use). Details from @HadrienGardeur welcome.

**Comment by HadrienGardeur** [comment]
Their practical use is to reference external documents as well and not just our own specification. For instance if an implementer rolls out its own profile and user specific terms, they should be documented in there.

**Comment by murata2makoto** [comment]
> All official link relations used in the License Document and declared in official LCP specification documents MUST be referenced in the registry.

This sentence obviously implies that conformance of the license document cannot be tested without examining the content of the LCP Link Relations Registry.  Thus, this registry has to be a normative reference.  And use of registries in ISO/IEC standards is now extremely difficult.

**Comment by llemeurfr** [comment]
I'm ok to modify this sentence, not to make registries normative :-)

**Comment by murata2makoto** [comment]
> All Encryption Profiles must be registered in the LCP Encryption Profiles registry, as explicitly explained in the registry.

The same comment here.

**Comment by llemeurfr** [comment]
So, @murata2makoto and @HadrienGardeur, would you agree to the following?

1/ Sentences which introduce registries (in 3.5 links, 3.6 rights, 3.7 user) are moved to 3.1 which is informative, and rephrased to be clearly not normative (it should indicate the existence of these registries).  

2/ The normative rule expressed in 6.2 (All Encryption Profiles must be registered in the LCP Encryption Profiles registry) is transformed into an informative sentence in 6.1 (informative intro). There is already a reference to the Profile registry in 6.1 by the way.

**Comment by llemeurfr** [comment]
The ISO draft clearly makes registries informative. The ISO language may be ported back to the Readium LCP spec later.
