### ISSUE TITLE
"official" in 3.5 of the LCP spec looks useless

### ISSUE THREAD

**Issue by murata2makoto** [readium/lcp-specs#28]
> All official link relations used in the License Document and declared in official LCP specification documents <b>MUST</b> be referenced in the registry.

What does "official" mean?  I also think that "and declared in official LCP specification documents" is unnecessary and confusing.

**Comment by llemeurfr** [comment]
I think the authors wanted to describe here all link relations that are part of the LCP specification, i.e. not those which may be vendor-specific extensions. 

The LCP Link Relation Registry is still to be created. It will be a simple md document in this "readium-lcp-spec" folder.

**Comment by llemeurfr** [comment]
We may decide to simplify the whole paragraphe (2 sentences) as:

> The link relations defined in this specification are also listed in the LCP Link Relations Registry. 

We find the same type of paragraph in 3.6 (Rights) and 3.7 (User). All could be simplified the same way.
