### ISSUE TITLE
Typo in JSON Schema: revoke vs. revoked

### ISSUE THREAD

**Issue by danielweck** [readium/lcp-specs#31]
https://github.com/readium/lcp-specs/blob/5828f83b6fffee23cbc38870f6f6431744191f21/schema/status.schema.json#L75

LSD event `revoked` should be `revoke`.

Spec. reference:
https://github.com/readium/lcp-specs/blob/master/lsd.md#27-events

**Comment by mmenu-mantano** [comment]
I just fixed the Swift parser to use `revoked` instead of `revoke`, using the JSON schema... 🙃

**Comment by HadrienGardeur** [comment]
This feels more like a typo in the spec IMO.

**Comment by llemeurfr** [comment]
I disagree. The spec is ok, we have chosen to use active terms in events, passive in status.

**Comment by HadrienGardeur** [comment]
Yeah... I just looked back at the rest of the value and it is indeed consistent with the rest of it.
