### ISSUE TITLE
audio, video and bitmap resources should not be deflated in the zip

### ISSUE THREAD

**Issue by llemeurfr** [readium/lcp-specs#32]
The exact wording is still to be found; binary files which are already compressed and will be processed using "seek" should be "stored" and not "deflated". 

We are missing such requirement in the specification.

**Comment by llemeurfr** [comment]
There is a question about fonts also.

**Comment by thkim2015** [comment]
The exact wording was already considered in EPUB 3.2 specification. 
[https://www.w3.org/publishing/epub/epub-ocf.html#sec-enc-compression](url)

**Comment by llemeurfr** [comment]
Fixed in #33
