### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by danielweck** [readium/lcp-specs#35]
https://readium.org/lcp-specs/readium-lcp-specification#generating-the-signature

should be:

https://readium.org/lcp-specs/readium-lcp-specification#54-generating-the-signature

**Comment by danielweck** [comment]
https://readium.org/lcp-specs/readium-lcp-specification#canonical-form-of-the-license-document

should be:

https://readium.org/lcp-specs/readium-lcp-specification#53-canonical-form-of-the-license-document

**Comment by danielweck** [comment]
https://readium.org/lcp-specs/readium-lcp-specification#validating-the-certificate-and-signature

should be:

https://readium.org/lcp-specs/readium-lcp-specification#55-validating-the-certificate-and-signature

**Comment by danielweck** [comment]
etc. ?
(there seems to be a pattern)

**Comment by HadrienGardeur** [comment]
This is due to the fact that we moved away from authoring these in HTML to using Mardown and letting Jekyll/Github Pages generate our anchors. Where did you encountered these links?

**Comment by danielweck** [comment]
I came across these links in the main spec. docs
https://readium.org/lcp-specs/readium-lcp-specification
(yesterday, before it became 404 ;)

**Comment by llemeurfr** [comment]
I'll fix that today.

**Comment by HadrienGardeur** [comment]
I took care of it, but left this issue open in case I missed a few.
