### ISSUE TITLE
How to implement the "renew" LSD interaction?

### ISSUE THREAD

**Issue by mickael-menu** [readium/lcp-specs#43]
I open this issue to discuss about the proper API to expose in the LCP client libraries for the renew LSD interaction.

From my understanding, we have three use cases offered by the spec:

1. An LSD templated link:
    a. with an `end` parameter -> the app should ask the user for the end date, before calling this link
    b. without `end` -> the app should call the link directly, and display a success or error message
2. An HTML renew link -> the reading app should present the URL in a web view

I assumed this order of precedence between these actions, because the spec doesn't say which one is preferred when we have both the LSD and HTML links.

---

Currently, this is the sub-par API we expose on mobile toolkits:

```kotlin
/**
 * Renews the loan up to a certain date (if possible).
 *
 * @param present: Used when the renew requires to present an HTML page to the user. The caller
 *        is responsible for presenting the URL and then calling the `dismissed` callback once the website
 *        is closed by the user.
 */
fun renewLoan(end: DateTime?, present: URLPresenter, completion: (LCPError?) -> Unit)

typealias URLPresenter = (URL, dismissed: () -> Unit) -> Unit
```

The issue is that we expect the app to provide an `end` date. This is not useful if there's only an HTML link or a LSD link without `end` parameter, and for now there's no easy way for an app to check if it should prompt the user for an end date or not.

To fix this, I suggest to invert the control with the introduction of a delegate. Either provided to the `LcpService`, or to the `renewLoan()` API directly.

```kotlin
/**
 * UX delegate for the renew LSD interaction.
 */
interface RenewListener {

    /**
     * Called when the renew interaction allows to customize the end date.
     * You can prompt the user for the number of days to renew, for example.
     */
    suspend fun retrieveEndDate(maximumDate: Date?): Date?

    /**
     * Called when the renew interaction uses an HTML web page.
     * You should present the URL in a Chrome Custom Tab.
     */
    suspend fun presentUrl(url: URL)

}

/**
 * Starts the renew LSD interaction.
 */
fun renewLoan(listener: RenewListener)
```

**Comment by mickael-menu** [comment]
I intend to implement this new API for the next beta of the mobile toolkit, since it would be a breaking change for a 2.1. Let me know if there's anything to review in this proposal.

(cc @HadrienGardeur @llemeurfr)

**Comment by llemeurfr** [comment]
The process described in the intro is fine. 
I'm just wondering if "presentUrl" is a proper name for a function which presents a renew extension Web page.

**Comment by mickael-menu** [comment]
How about `openWebPage()` or `openUrl()`?

Note that this is a request to the client to do an atomic task: presenting a web page in a web view. So I don't think naming this `renewWeb()` would fit.

**Comment by mickael-menu** [comment]
Here's the API I came up with in the end, in the Kotlin PR. I added a `prefersWebPage` parameter which can be used for two things:

* For apps that always prefer the web page option when available, instead of renewing programmatically.
* For apps trying to recover from a failure using the web page option.

By default, the implementation prefers a programmatic renew over a web page.

```kotlin
   /**
     * Renews the loan by starting a renew LSD interaction.
     *
     * @param prefersWebPage Indicates whether the loan should be renewed through a web page if
     *        available, instead of programmatically.
     */
    suspend fun renewLoan(listener: RenewListener, prefersWebPage: Boolean = false): Try<Date?, LcpException>
```

```kotlin
    /**
     * UX delegate for the loan renew LSD interaction.
     *
     * If your application fits Material Design guidelines, take a look at [MaterialRenewListener]
     * for a default implementation.
     */
    interface RenewListener {

        /**
         * Called when the renew interaction allows to customize the end date programmatically.
         * You can prompt the user for the number of days to renew, for example.
         *
         * The returned date can't exceed [maximumDate].
         */
        suspend fun preferredEndDate(maximumDate: Date?): Date?

        /**
         * Called when the renew interaction uses an HTML web page.
         *
         * You should present the URL in a Chrome Custom Tab and terminate the function when the
         * web page is dismissed by the user.
         */
        suspend fun openWebPage(url: URL)

    }
```
