### ISSUE TITLE
address privacy implications of device ids

### ISSUE THREAD

**Issue by eshellman** [readium/lcp-specs#5]
Device IDs can be used to identify users. For example, MAC addresses are broadcast by a device to establish wifi connections. Modern operating systems allow these addresses to be generated dynamically, and we can expect this behavior to be more common as operating systems respond to privacy threats. Persistent device ids can be used to track users, much as advertising networks use tracking cookies to establish demographic profiles for advertising targeting; they exchange tracking ids promiscuously. For these reasons, the registration operation can be expected to degrade both user privacy and become less effective at controlling the number of devices that access a particular license.

For these reasons, I suggest that instead of "device" id, an installation id, or a random key generated during software installation be used. This will improve the viability of the registration process and prevent the correlation of registration data with independently collected tracking data. I would also suggest that a different installation id be sent for each provider, to prevent providers from exchanging registration data for purposes of user tracking.

**Comment by HadrienGardeur** [comment]
This IMO seems more tied to the implementation than the specification.

Main issue that I could see with a random id, is that the same device could then be counted as two registrations or more.

**Comment by danielweck** [comment]
FYI
The open-source ReadiumSDK "launcher" apps (Android, iOS, OSX) which are used to test the LCP client lib currently all create their "device id" based on a randomly-generated UUID, made persistent in local app settings, therefore only unique for the lifetime of the installed app (in other words: uninstalled + reinstalled app gets new device ID).

**Comment by eshellman** [comment]
@danielweck that's good to hear, but privacy considerations should be in the spec. If implementers are allowed to do privacy wrong, they will.

**Comment by HadrienGardeur** [comment]
I don't think that the spec should enforce this through MUST, but a few SHOULD could be added.

It's the role of the certification process to enforce such restrictions.

**Comment by eshellman** [comment]
Would you like me to draft a PR?
