### ISSUE TITLE
address denial-of-service attacks on the registration process

### ISSUE THREAD

**Issue by eshellman** [readium/lcp-specs#6]
Though the current documentation doesn't say so explicitly, I'm assuming that registration URLs will be included in the links block of the (unencrypted) license document. 

the suggested format of the link is http://example.org/license/aaa-bbbb-ccc/register{?id,name}

PR #4 fixes the insecure protocol of the example. I believe that the spec already requires it to be secure.

aaa-bbbb-ccc identifies the license.
id identifies a device (also see issue #5 )

if the license id is exposed or if the id can be predicted (for example by using [isbn].[user bar code], the provider is vulnerable to an attack where the attacker asserts a registration for large numbers of [fake] devices, triggering a spurious license invalidation.

This can be addressed by use of a (large) random license id, and by specifying that license ids should not be made public and handled securely.

**Comment by HadrienGardeur** [comment]
The only part that's suggested is the URI template so `{?id,name}`, the rest is just an example.

Each server is then responsible for its implementation, but the most common thing to do would be to use a UUID to avoid collisions.

Also, the URI doesn't actually need to have a license id at all. You could for instance use a JWT or another type of hash.

**Comment by eshellman** [comment]
Yes, a UUID would be a good practice, but the server still needs to be able to trust the ecosystem that the UUID is not made available to attackers.

**Comment by HadrienGardeur** [comment]
Not sure what you mean by "made available to attackers". Good luck brute forcing a service by randomly generating UUIDs.

If you mean that the provider's database could be stolen and then the UUIDs extracted from there, then sure that's a problem, but a DoS would be the least of their concern in that case.

**Comment by eshellman** [comment]
Publishers share information for legitimate reasons all the time. Suppose for example, that authors were provided the license id's as part of royalty accounting. There are some proposals for blockchain license registries. The license ids might be the target of legal process. Whatever, providers should be aware that license ids can be misused.

**Comment by HadrienGardeur** [comment]
But the license ID has nothing to do with the URI, you can't guess a URI by knowing the license id. 

It all depends on implementations, which is one of the reason why there's a certification involved in a shared ecosystem. IMO the best thing to do is to use a JWT or similar mechanism to have a signed token in there that can't be tampered or generated in a brute force attack.

**Comment by eshellman** [comment]
I agree this is an implementation detail, but a good spec is one helps implementers avoid implementation mistakes such as using license ids as the URI.

**Comment by HadrienGardeur** [comment]
I agree, could you make a pull request with a proposal to improve these examples?

**Comment by eshellman** [comment]
OK, I will.
