### ISSUE TITLE
Missing registry documents

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/lcp-specs#8]
While the main LCP specification mentions a number of registries, none of them have been created and there are no links to them.

We need to create such registries and host them on this repo (easiest solution for PR).

**Comment by HadrienGardeur** [comment]
Bumping this up cc @llemeurfr

**Comment by murata2makoto** [comment]
See my comments on #27.

**Comment by llemeurfr** [comment]
Registries are now created.
